---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
    app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
  labels:
    app.kubernetes.io/name: shopping-service
    app.kubernetes.io/version: 1.0.5-SNAPSHOT
  name: shopping-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
    app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
  labels:
    app.kubernetes.io/name: shopping-service
    app.kubernetes.io/version: 1.0.5-SNAPSHOT
  name: shopping-service
spec:
  ports:
  - name: http
    port: 8090
    targetPort: 8090
  selector:
    app.kubernetes.io/name: shopping-service
    app.kubernetes.io/version: 1.0.5-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: shopping-service
    app.kubernetes.io/version: 1.0.5-SNAPSHOT
  name: shopping-service:admin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin
subjects:
- kind: ServiceAccount
  name: shopping-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
    app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
  labels:
    app.kubernetes.io/name: shopping-service
    app.kubernetes.io/version: 1.0.5-SNAPSHOT
  name: shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shopping-service
      app.kubernetes.io/version: 1.0.5-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
        app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
      labels:
        app.kubernetes.io/name: shopping-service
        app.kubernetes.io/version: 1.0.5-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: performancetuningcontainerregistry.azurecr.cn/shopping-service:1.0.5-SNAPSHOT
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/info
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: shopping-service
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccountName: shopping-service
