---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.10-SNAPSHOT
  name: account-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
    app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.10-SNAPSHOT
  name: account-service
spec:
  ports:
    - name: http
      port: 9003
      targetPort: 9003
  selector:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.10-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
    app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.10-SNAPSHOT
  name: account-service:cluster-admin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: account-service
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
    app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.10-SNAPSHOT
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: account-service
      app.kubernetes.io/version: 1.0.10-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/commit-id: dc06b849c64d13f14cabe9f6acffba3710c9af14
        app.dekorate.io/vcs-url: https://dev.azure.com/sme-csu/cloud-native-apps-performance/_git/cloud-native-apps-performance-tuning.git
      labels:
        app.kubernetes.io/name: account-service
        app.kubernetes.io/version: 1.0.10-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: performancetuningcontainerregistry.azurecr.cn/account-service:1.0.10-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/info
              port: 9003
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: account-service
          ports:
            - containerPort: 9003
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9003
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: account-service